var info = `
-TEAM The Floaters
VB SandyBrown P
BG SandyBrown X
MO SandyBrown X
AC SandyBrown P
LF SandyBrown X
AK SandyBrown X
-TEAM Generic team name
CH mediumpurple P
LD mediumpurple X
TS mediumpurple P
JC mediumpurple X
PB mediumpurple X
BJ mediumpurple X
-TEAM TEAM AINLEY
RA hotpink X
KM hotpink X
GF hotpink X
EH hotpink X
LM hotpink X
MH hotpink X
-TEAM TEAM HOWE
MH firebrick P
SM firebrick P
DC firebrick X
MN firebrick P
CA firebrick P
EL firebrick X
-TEAM Trust Team
PB dodgerblue P
DG dodgerblue P
JM dodgerblue P
PH dodgerblue P
JG dodgerblue P
CH dodgerblue P
-TEAM AW Science
RC darkgreen X
AL darkgreen X
CL darkgreen X
TH darkgreen X
RM darkgreen P
?? black X
-TEAM TEAM Colley
GC darkgoldenrod P
CF darkgoldenrod P
JB darkgoldenrod P
AB darkgoldenrod X
FG darkgoldenrod X
?? black X
-TEAM TEAM King
GK yellowgreen X
BP yellowgreen X
RB yellowgreen X
KW yellowgreen X
DL yellowgreen X
PB yellowgreen X
-TEAM AW Maths
BH red P
JH red P
TW red P
RP red P
JJ red P
RC red P
-TEAM BC S Team
HG slategray P
HM slategray X
JR slategray P
SM slategray X
DR slategray X
KW slategray X
-TEAM BC Science
RI navy P
NR navy P
EV navy P
AP navy P
TW navy P
EP navy P
-TEAM Andrews
SA Fuchsia X
CT Fuchsia X
JB Fuchsia X
LT Fuchsia X
SZ Fuchsia X
KK Fuchsia X
-TEAM Team ...
LB darkorange X
GR darkorange X
SA darkorange X
JF darkorange X
?? black X
?? black X
`
