var info = `
-TEAM The Floaters
VB SandyBrown P
BG SandyBrown X
MO SandyBrown X
AC SandyBrown X
LF SandyBrown X
AK SandyBrown X
-TEAM Generic team name
CH mediumpurple P
LD mediumpurple X
TS mediumpurple P
JC mediumpurple X
PB mediumpurple X
BJ mediumpurple X
-TEAM TEAM AINLEY
RA hotpink X
KM hotpink X
GF hotpink X
EH hotpink X
LM hotpink X
MH hotpink X
-TEAM TEAM HOWE
MH firebrick P
SM firebrick P
DC firebrick X
MN firebrick X
CA firebrick X
EL firebrick X
-TEAM Trust Team
PB dodgerblue P
DG dodgerblue P
JM dodgerblue P
PH dodgerblue P
JG dodgerblue P
CH dodgerblue P
-TEAM AW Science
RC darkgreen X
AL darkgreen X
CL darkgreen X
TH darkgreen X
RM darkgreen X
?? black X
-TEAM TEAM Colley
GC darkgoldenrod X
CF darkgoldenrod X
JB darkgoldenrod X
AB darkgoldenrod X
FG darkgoldenrod X
?? black X
-TEAM TEAM King
GK yellowgreen X
BP yellowgreen X
RB yellowgreen X
KW yellowgreen X
?? black X
?? black X
-TEAM OTHERS
?? black X
?? black X
?? black X
?? black X
?? black X
?? black X
-TEAM NONE
?? black X
?? black X
?? black X
?? black X
?? black X
?? black X
-TEAM NONE
?? black X
?? black X
?? black X
?? black X
?? black X
?? black X
-TEAM NONE
?? black X
?? black X
?? black X
?? black X
?? black X
?? black X
`
